apiVersion: v2
name: cloudcasa
version: "3.4.5"
appVersion: "3.1.0"
kubeVersion: ">=1.20.0-0"
description: CloudCasa backup and migration service agent for Kubernetes
annotations:
  charts.openshift.io/name: CloudCasa Agent
home: https://cloudcasa.io
icon: https://raw.githubusercontent.com/catalogicsoftware/cloudcasa-helmchart/gh-pages/logo.png
keywords:
  - backup
  - restore
  - migration
  - catalogic
  - cloudcasa
  - velero
maintainers:
  - name: CloudCasa Support
    email: support@cloudcasa.io
